/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedCarteiraRouteImport } from './routes/_authenticated/carteira'
import { Route as AuthenticatedOfertasRouteImport } from './routes/_authenticated/ofertas'
import { Route as AuthenticatedSuporteRouteImport } from './routes/_authenticated/suporte'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedAdminGerenciarTarefasRouteImport } from './routes/_authenticated/admin/gerenciar-tarefas'
import { Route as AuthenticatedTarefasIndexRouteImport } from './routes/_authenticated/tarefas/index'
import { Route as AuthenticatedTarefasIdRouteImport } from './routes/_authenticated/tarefas/$id'
import { Route as ApiPublicAdgemPostbackRouteImport } from './routes/api/public/adgem-postback'
import { Route as ApiPublicAsaasWebhookRouteImport } from './routes/api/public/asaas-webhook'
import { Route as ApiPublicBitlabsWebhookRouteImport } from './routes/api/public/bitlabs-webhook'
import { Route as ApiPublicJotformPrecadastroRouteImport } from './routes/api/public/jotform-precadastro'
import { Route as ApiPublicPostbackRouteImport } from './routes/api/public/postback'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCarteiraRoute = AuthenticatedCarteiraRouteImport.update({
  id: '/carteira',
  path: '/carteira',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOfertasRoute = AuthenticatedOfertasRouteImport.update({
  id: '/ofertas',
  path: '/ofertas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSuporteRoute = AuthenticatedSuporteRouteImport.update({
  id: '/suporte',
  path: '/suporte',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminGerenciarTarefasRoute =
  AuthenticatedAdminGerenciarTarefasRouteImport.update({
    id: '/admin/gerenciar-tarefas',
    path: '/admin/gerenciar-tarefas',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTarefasIndexRoute =
  AuthenticatedTarefasIndexRouteImport.update({
    id: '/tarefas/',
    path: '/tarefas/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTarefasIdRoute = AuthenticatedTarefasIdRouteImport.update({
  id: '/tarefas/$id',
  path: '/tarefas/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicAdgemPostbackRoute = ApiPublicAdgemPostbackRouteImport.update({
  id: '/api/public/adgem-postback',
  path: '/api/public/adgem-postback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAsaasWebhookRoute = ApiPublicAsaasWebhookRouteImport.update({
  id: '/api/public/asaas-webhook',
  path: '/api/public/asaas-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBitlabsWebhookRoute = ApiPublicBitlabsWebhookRouteImport.update({
  id: '/api/public/bitlabs-webhook',
  path: '/api/public/bitlabs-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicJotformPrecadastroRoute =
  ApiPublicJotformPrecadastroRouteImport.update({
    id: '/api/public/jotform-precadastro',
    path: '/api/public/jotform-precadastro',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicPostbackRoute = ApiPublicPostbackRouteImport.update({
  id: '/api/public/postback',
  path: '/api/public/postback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/carteira': typeof AuthenticatedCarteiraRoute
  '/ofertas': typeof AuthenticatedOfertasRoute
  '/suporte': typeof AuthenticatedSuporteRoute
  '/admin/gerenciar-tarefas': typeof AuthenticatedAdminGerenciarTarefasRoute
  '/tarefas/$id': typeof AuthenticatedTarefasIdRoute
  '/api/public/adgem-postback': typeof ApiPublicAdgemPostbackRoute
  '/api/public/asaas-webhook': typeof ApiPublicAsaasWebhookRoute
  '/api/public/bitlabs-webhook': typeof ApiPublicBitlabsWebhookRoute
  '/api/public/jotform-precadastro': typeof ApiPublicJotformPrecadastroRoute
  '/api/public/postback': typeof ApiPublicPostbackRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/tarefas/': typeof AuthenticatedTarefasIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/carteira': typeof AuthenticatedCarteiraRoute
  '/ofertas': typeof AuthenticatedOfertasRoute
  '/suporte': typeof AuthenticatedSuporteRoute
  '/admin/gerenciar-tarefas': typeof AuthenticatedAdminGerenciarTarefasRoute
  '/tarefas/$id': typeof AuthenticatedTarefasIdRoute
  '/api/public/adgem-postback': typeof ApiPublicAdgemPostbackRoute
  '/api/public/asaas-webhook': typeof ApiPublicAsaasWebhookRoute
  '/api/public/bitlabs-webhook': typeof ApiPublicBitlabsWebhookRoute
  '/api/public/jotform-precadastro': typeof ApiPublicJotformPrecadastroRoute
  '/api/public/postback': typeof ApiPublicPostbackRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/tarefas': typeof AuthenticatedTarefasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/carteira': typeof AuthenticatedCarteiraRoute
  '/_authenticated/ofertas': typeof AuthenticatedOfertasRoute
  '/_authenticated/suporte': typeof AuthenticatedSuporteRoute
  '/_authenticated/admin/gerenciar-tarefas': typeof AuthenticatedAdminGerenciarTarefasRoute
  '/_authenticated/tarefas/$id': typeof AuthenticatedTarefasIdRoute
  '/api/public/adgem-postback': typeof ApiPublicAdgemPostbackRoute
  '/api/public/asaas-webhook': typeof ApiPublicAsaasWebhookRoute
  '/api/public/bitlabs-webhook': typeof ApiPublicBitlabsWebhookRoute
  '/api/public/jotform-precadastro': typeof ApiPublicJotformPrecadastroRoute
  '/api/public/postback': typeof ApiPublicPostbackRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/tarefas/': typeof AuthenticatedTarefasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/carteira'
    | '/ofertas'
    | '/suporte'
    | '/admin/gerenciar-tarefas'
    | '/tarefas/$id'
    | '/api/public/adgem-postback'
    | '/api/public/asaas-webhook'
    | '/api/public/bitlabs-webhook'
    | '/api/public/jotform-precadastro'
    | '/api/public/postback'
    | '/admin/'
    | '/tarefas/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/carteira'
    | '/ofertas'
    | '/suporte'
    | '/admin/gerenciar-tarefas'
    | '/tarefas/$id'
    | '/api/public/adgem-postback'
    | '/api/public/asaas-webhook'
    | '/api/public/bitlabs-webhook'
    | '/api/public/jotform-precadastro'
    | '/api/public/postback'
    | '/admin'
    | '/tarefas'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/carteira'
    | '/_authenticated/ofertas'
    | '/_authenticated/suporte'
    | '/_authenticated/admin/gerenciar-tarefas'
    | '/_authenticated/tarefas/$id'
    | '/api/public/adgem-postback'
    | '/api/public/asaas-webhook'
    | '/api/public/bitlabs-webhook'
    | '/api/public/jotform-precadastro'
    | '/api/public/postback'
    | '/_authenticated/admin/'
    | '/_authenticated/tarefas/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicAdgemPostbackRoute: typeof ApiPublicAdgemPostbackRoute
  ApiPublicAsaasWebhookRoute: typeof ApiPublicAsaasWebhookRoute
  ApiPublicBitlabsWebhookRoute: typeof ApiPublicBitlabsWebhookRoute
  ApiPublicJotformPrecadastroRoute: typeof ApiPublicJotformPrecadastroRoute
  ApiPublicPostbackRoute: typeof ApiPublicPostbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/carteira': {
      id: '/_authenticated/carteira'
      path: '/carteira'
      fullPath: '/carteira'
      preLoaderRoute: typeof AuthenticatedCarteiraRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ofertas': {
      id: '/_authenticated/ofertas'
      path: '/ofertas'
      fullPath: '/ofertas'
      preLoaderRoute: typeof AuthenticatedOfertasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/suporte': {
      id: '/_authenticated/suporte'
      path: '/suporte'
      fullPath: '/suporte'
      preLoaderRoute: typeof AuthenticatedSuporteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/gerenciar-tarefas': {
      id: '/_authenticated/admin/gerenciar-tarefas'
      path: '/admin/gerenciar-tarefas'
      fullPath: '/admin/gerenciar-tarefas'
      preLoaderRoute: typeof AuthenticatedAdminGerenciarTarefasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tarefas/': {
      id: '/_authenticated/tarefas/'
      path: '/tarefas'
      fullPath: '/tarefas/'
      preLoaderRoute: typeof AuthenticatedTarefasIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tarefas/$id': {
      id: '/_authenticated/tarefas/$id'
      path: '/tarefas/$id'
      fullPath: '/tarefas/$id'
      preLoaderRoute: typeof AuthenticatedTarefasIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/adgem-postback': {
      id: '/api/public/adgem-postback'
      path: '/api/public/adgem-postback'
      fullPath: '/api/public/adgem-postback'
      preLoaderRoute: typeof ApiPublicAdgemPostbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/asaas-webhook': {
      id: '/api/public/asaas-webhook'
      path: '/api/public/asaas-webhook'
      fullPath: '/api/public/asaas-webhook'
      preLoaderRoute: typeof ApiPublicAsaasWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/bitlabs-webhook': {
      id: '/api/public/bitlabs-webhook'
      path: '/api/public/bitlabs-webhook'
      fullPath: '/api/public/bitlabs-webhook'
      preLoaderRoute: typeof ApiPublicBitlabsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/jotform-precadastro': {
      id: '/api/public/jotform-precadastro'
      path: '/api/public/jotform-precadastro'
      fullPath: '/api/public/jotform-precadastro'
      preLoaderRoute: typeof ApiPublicJotformPrecadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/postback': {
      id: '/api/public/postback'
      path: '/api/public/postback'
      fullPath: '/api/public/postback'
      preLoaderRoute: typeof ApiPublicPostbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCarteiraRoute: typeof AuthenticatedCarteiraRoute
  AuthenticatedOfertasRoute: typeof AuthenticatedOfertasRoute
  AuthenticatedSuporteRoute: typeof AuthenticatedSuporteRoute
  AuthenticatedAdminGerenciarTarefasRoute: typeof AuthenticatedAdminGerenciarTarefasRoute
  AuthenticatedTarefasIdRoute: typeof AuthenticatedTarefasIdRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedTarefasIndexRoute: typeof AuthenticatedTarefasIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCarteiraRoute: AuthenticatedCarteiraRoute,
  AuthenticatedOfertasRoute: AuthenticatedOfertasRoute,
  AuthenticatedSuporteRoute: AuthenticatedSuporteRoute,
  AuthenticatedAdminGerenciarTarefasRoute:
    AuthenticatedAdminGerenciarTarefasRoute,
  AuthenticatedTarefasIdRoute: AuthenticatedTarefasIdRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedTarefasIndexRoute: AuthenticatedTarefasIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicAdgemPostbackRoute: ApiPublicAdgemPostbackRoute,
  ApiPublicAsaasWebhookRoute: ApiPublicAsaasWebhookRoute,
  ApiPublicBitlabsWebhookRoute: ApiPublicBitlabsWebhookRoute,
  ApiPublicJotformPrecadastroRoute: ApiPublicJotformPrecadastroRoute,
  ApiPublicPostbackRoute: ApiPublicPostbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
